services:
  dev:
    build:
      context: "./"
      dockerfile: "dev.Dockerfile"
    ports:
      - "4045:4045"
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./Makefile:/app/Makefile
    tty: true
    profiles:
      - dev

  prod:
    image: "ercross/grabjobs:latest"

    # uncomment build to build image locally
    # https://docs.docker.com/compose/compose-file/#pull_policy
    #build:
      #context: "./"
      #dockerfile: "prod.Dockerfile"
    ports:
      - "4045:4045"
    entrypoint: ./bin/grabjobs -port 4045 -db 'res/location_data.csv'
    profiles:
      - production
